[book]
authors = ["chenxuan520"]
language = "zh"
multilingual = false
src = "src"
title = "chenxuan520'blog"
description= "chenxuan520'blog"

[output.html]
# defaulr dark theme
default-theme = "navy"
# for Chinese search
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js", "assets/reference.js", "assets/highlight.js", "theme/pagetoc.js"]
additional-css = ["assets/utils.css", "theme/pagetoc.css"]
# set for github icon
git-repository-url = "https://github.com/chenxuanweb/obsidiandemo"
git-repository-icon = "fa-github"
